/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipr.projekt.zakladki;

import ipr.projekt.classes.DruzynyK;
import ipr.projekt.classes.MeczK;
import ipr.projekt.program.MainWindow;
import ipr.projekt.program.MySql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Michal
 */
public class Mecze extends javax.swing.JPanel {

    Map<String, String> sortMap = new HashMap<String, String>();
    boolean szukajWszystkie = true;
    MainWindow parentFrame;

    MeczK meczK = MeczK.getInstance();

    /**
     * Creates new form Mecze
     */
    public Mecze(MainWindow parentFrame) {

        this.parentFrame = parentFrame;

        initComponents();

        initPanelBoczny();

        wyszukajWszystko();

        initClass();
    }

    public void odswierzZakladke() {

        StringBuilder builder = new StringBuilder();
        builder.append("SELECT ");

        Connection connection = MySql.getInstance().getConnection();
        try {
            PreparedStatement ps = connection.prepareStatement(builder.toString());
        } catch (SQLException ex) {
            Logger.getLogger(Mecze.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDruzyna1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbDruzyna2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbSort = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbDzienOd = new javax.swing.JComboBox();
        cbMiesiacOd = new javax.swing.JComboBox();
        cbRokOd = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbDzienDo = new javax.swing.JComboBox();
        cbMiesiacDo = new javax.swing.JComboBox();
        cbRokDo = new javax.swing.JComboBox();
        btnFiltruj = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();

        cbDruzyna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDruzyna1ActionPerformed(evt);
            }
        });

        jLabel1.setText("vs.");

        jButton1.setText("Wyszukaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Wyszystkie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Sortuj wg.:");

        jLabel3.setText("Okres");

        jLabel4.setText("Od:");

        jLabel5.setText("Do:");

        btnFiltruj.setText("Filtruj okres");
        btnFiltruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrujActionPerformed(evt);
            }
        });

        btnSort.setText("Sortuj");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRokOd, 0, 184, Short.MAX_VALUE)
                    .addComponent(cbRokDo, 0, 184, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(btnFiltruj)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDzienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(btnSort))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSort)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRokOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDzienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbRokDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltruj)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDruzyna1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDruzyna2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDruzyna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cbDruzyna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDruzyna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDruzyna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDruzyna1ActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        Object[][] tableaBody = null;
        if (szukajWszystkie) {
            tableaBody = meczK.getMecze(null, null, sortMap.get((String) cbSort.getSelectedItem()), null, null, true, false);
        } else {
            String dr1 = (String) cbDruzyna1.getSelectedItem();
            String dr2 = (String) cbDruzyna2.getSelectedItem();
            tableaBody = meczK.getMecze(dr1, dr2, sortMap.get((String) cbSort.getSelectedItem()), null, null, true, false);
        }
        String[] tablaHead = {"#", "Gospodarze", "Goście", "Data", "Wyniki", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnFiltrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrujActionPerformed
        Date dataOd = new Date(
                Integer.parseInt((String) cbRokOd.getSelectedItem()) - 1900,
                Integer.parseInt((String) cbMiesiacOd.getSelectedItem()) - 1,
                Integer.parseInt((String) cbDzienOd.getSelectedItem())
        );
        Date dataDo = new Date(
                Integer.parseInt((String) cbRokDo.getSelectedItem()) - 1900,
                Integer.parseInt((String) cbMiesiacDo.getSelectedItem()) - 1,
                Integer.parseInt((String) cbDzienDo.getSelectedItem())
        );
        Object[][] tableaBody = null;
        if (szukajWszystkie) {
            tableaBody = meczK.getMecze(null, null, null, dataOd, dataDo, false, true);
        } else {
            String dr1 = (String) cbDruzyna1.getSelectedItem();
            String dr2 = (String) cbDruzyna2.getSelectedItem();
            tableaBody = meczK.getMecze(dr1, dr2, null, dataOd, dataDo, false, true);
        }
        String[] tablaHead = {"#", "Gospodarze", "Goście", "Data", "Wyniki", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }//GEN-LAST:event_btnFiltrujActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wyszukaj();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        wyszukajWszystko();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        String id = (String) jTable1.getValueAt(jTable1.rowAtPoint(evt.getPoint()), 5);
        parentFrame.switchMeczTab(Integer.parseInt(id));
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltruj;
    private javax.swing.JButton btnSort;
    private javax.swing.JComboBox cbDruzyna1;
    private javax.swing.JComboBox cbDruzyna2;
    private javax.swing.JComboBox cbDzienDo;
    private javax.swing.JComboBox cbDzienOd;
    private javax.swing.JComboBox cbMiesiacDo;
    private javax.swing.JComboBox cbMiesiacOd;
    private javax.swing.JComboBox cbRokDo;
    private javax.swing.JComboBox cbRokOd;
    private javax.swing.JComboBox cbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void wyszukaj() {
        String dr1 = (String) cbDruzyna1.getSelectedItem();
        String dr2 = (String) cbDruzyna2.getSelectedItem();
        Object[][] tableaBody = meczK.getMecze(dr1, dr2, null, null, null, false, false);
        String[] tablaHead = {"#", "Gospodarze", "Goście", "Data", "Wyniki", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }

    private void initPanelBoczny() {
        List<String> dzien = new ArrayList<String>();
        for (int i = 1; i < 32; i++) {
            dzien.add("" + i);
        }
        List<String> miesiac = new ArrayList<String>();
        for (int i = 1; i < 13; i++) {
            miesiac.add("" + i);
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);

        List<String> rok = new ArrayList<String>();
        for (int i = 0; i < 121; i++) {
            int rok2 = year - i;
            rok.add("" + rok2);
        }

        cbDzienDo.setModel(new DefaultComboBoxModel(dzien.toArray()));
        cbDzienOd.setModel(new DefaultComboBoxModel(dzien.toArray()));

        cbMiesiacDo.setModel(new DefaultComboBoxModel(miesiac.toArray()));
        cbMiesiacOd.setModel(new DefaultComboBoxModel(miesiac.toArray()));

        cbRokDo.setModel(new DefaultComboBoxModel(rok.toArray()));
        cbRokOd.setModel(new DefaultComboBoxModel(rok.toArray()));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Gospodarze", "Goście", "Data"}));

        sortMap.put("Gospodarze", "gosp");
        sortMap.put("Goście", "gosc");
        sortMap.put("Data", "data");
    }

    private void initClass() {
        String[] druzyny = DruzynyK.getInstance().getDruzyny();
        cbDruzyna1.setModel(new javax.swing.DefaultComboBoxModel(druzyny));
        cbDruzyna2.setModel(new javax.swing.DefaultComboBoxModel(druzyny));
    }

    private void wyszukajWszystko() {
        Object[][] tableaBody = meczK.getMecze(null, null, null, null, null, false, false);
        String[] tablaHead = {"#", "Gospodarze", "Goście", "Data", "Wyniki", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }
}
