/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipr.projekt.zakladki;

import ipr.projekt.classes.DruzynyK;
import ipr.projekt.classes.MeczK;
import ipr.projekt.dialogi.WprowadzWynik;
import ipr.projekt.model.Zaklad;
import ipr.projekt.model.ZakladSkladowy;
import ipr.projekt.program.MainWindow;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Michal
 */
public class ZawrzyjZaklad extends javax.swing.JPanel {

    private MainWindow parentFrame;
    Map<String, String> sortMap = new HashMap<String, String>();

    /**
     * Creates new form ZawrzyjZaklad
     */
    public ZawrzyjZaklad(MainWindow parentFrame) {
        this.parentFrame = parentFrame;

        initComponents();

        initPanelBoczny();

        wyszukajWszystko();

        initClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbDruzyna1 = new javax.swing.JComboBox();
        cbDruzyna2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbSort = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDzienOd = new javax.swing.JComboBox();
        cbMiesiacOd = new javax.swing.JComboBox();
        cbRokOd = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cbDzienDo = new javax.swing.JComboBox();
        cbMiesiacDo = new javax.swing.JComboBox();
        cbRokDo = new javax.swing.JComboBox();
        btnFiltruj = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("Wyszukaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Wyszystkie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbDruzyna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDruzyna1ActionPerformed(evt);
            }
        });

        jLabel1.setText("vs.");

        jButton2.setText("Mój zakład");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Sortuj wg.:");

        jLabel7.setText("Okres");

        jLabel8.setText("Od:");

        jLabel9.setText("Do:");

        btnFiltruj.setText("Filtruj okres");

        btnSort.setText("Sortuj");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbSort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbDzienDo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRokOd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbRokDo, 0, 80, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(btnFiltruj))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnSort))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSort)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRokOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDzienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRokDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFiltruj)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Gospodzrze", "Goście", "Data", "Kurs", "Dodaj", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDruzyna1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDruzyna2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDruzyna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbDruzyna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        wyszukajWszystko();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbDruzyna1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDruzyna1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDruzyna1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        parentFrame.switchZakladTab();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int dodajCol = 4;
        if (jTable1.columnAtPoint(evt.getPoint()) == dodajCol) {
            int id_meczu = (int) jTable1.getValueAt(jTable1.rowAtPoint(evt.getPoint()), 5);
            if ((boolean) jTable1.getValueAt(jTable1.rowAtPoint(evt.getPoint()), 4)) {

                WprowadzWynik wprowadzWynik = new WprowadzWynik(null, true, id_meczu, (String) jTable1.getValueAt(jTable1.rowAtPoint(evt.getPoint()), 0), (String) jTable1.getValueAt(jTable1.rowAtPoint(evt.getPoint()), 1));
                wprowadzWynik.setVisible(true);
                if (wprowadzWynik.idAdded()) {
                    jTable1.setValueAt(true, jTable1.rowAtPoint(evt.getPoint()), jTable1.columnAtPoint(evt.getPoint()));
                } else {
                    jTable1.setValueAt(false, jTable1.rowAtPoint(evt.getPoint()), jTable1.columnAtPoint(evt.getPoint()));
                }
            } else {
                Zaklad.getInstance().deleteZakladSkladowy(new ZakladSkladowy(id_meczu, 0, (short)0, (short)0));
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltruj;
    private javax.swing.JButton btnSort;
    private javax.swing.JComboBox cbDruzyna1;
    private javax.swing.JComboBox cbDruzyna2;
    private javax.swing.JComboBox cbDzienDo;
    private javax.swing.JComboBox cbDzienOd;
    private javax.swing.JComboBox cbMiesiacDo;
    private javax.swing.JComboBox cbMiesiacOd;
    private javax.swing.JComboBox cbRokDo;
    private javax.swing.JComboBox cbRokOd;
    private javax.swing.JComboBox cbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void wyszukaj() {
        String dr1 = (String) cbDruzyna1.getSelectedItem();
        String dr2 = (String) cbDruzyna2.getSelectedItem();
        Object[][] tableaBody = MeczK.getInstance().getMecze(dr1, dr2, null, null, null, false, false);
        String[] tablaHead = {"#", "Gospodarze", "Goście", "Data", "Wyniki", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ));
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }

    private void initPanelBoczny() {

        List<String> dzien = new ArrayList<String>();
        for (int i = 1; i < 32; i++) {
            dzien.add("" + i);
        }
        List<String> miesiac = new ArrayList<String>();
        for (int i = 1; i < 13; i++) {
            miesiac.add("" + i);
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);

        List<String> rok = new ArrayList<String>();
        for (int i = 0; i < 121; i++) {
            int rok2 = year - i;
            rok.add("" + rok2);
        }

        cbDzienDo.setModel(new DefaultComboBoxModel(dzien.toArray()));
        cbDzienOd.setModel(new DefaultComboBoxModel(dzien.toArray()));

        cbMiesiacDo.setModel(new DefaultComboBoxModel(miesiac.toArray()));
        cbMiesiacOd.setModel(new DefaultComboBoxModel(miesiac.toArray()));

        cbRokDo.setModel(new DefaultComboBoxModel(rok.toArray()));
        cbRokOd.setModel(new DefaultComboBoxModel(rok.toArray()));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Gospodarze", "Goście", "Data"}));

        sortMap.put("Gospodarze", "gosp");
        sortMap.put("Goście", "gosc");
        sortMap.put("Data", "data");
    }

    private void initClass() {
        String[] druzyny = DruzynyK.getInstance().getDruzyny();
        cbDruzyna1.setModel(new javax.swing.DefaultComboBoxModel(druzyny));
        cbDruzyna2.setModel(new javax.swing.DefaultComboBoxModel(druzyny));
    }

    private void wyszukajWszystko() {
        Object[][] tableaBody = MeczK.getInstance().getMeczeZaklad(null, null, null, null, null, false, false);
        String[] tablaHead = {"Gospodarze", "Goście", "Data", "Kurs", "Dodaj", "ID"};
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                tableaBody,
                tablaHead
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.getColumnModel().getColumn(tablaHead.length - 1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(tablaHead.length - 1).setMaxWidth(0);
    }
    
    public void odswiezZakladke(){
        wyszukajWszystko();
    }
}
