/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipr.projekt.dialogi;

import ipr.projekt.model.Zaklad;
import javax.swing.JOptionPane;
import ipr.projekt.model.ZakladSkladowy;

/**
 *
 * @author Michal
 */
public class WprowadzWynik extends javax.swing.JDialog {

    private int idMeczu;
    private float kurs;
    private boolean added = false;

    /**
     * Creates new form WprowadzWynik
     */
    public WprowadzWynik(java.awt.Frame parent, boolean modal, int idMeczu, String gospodarze, String goscie) {
        super(parent, modal);
        initComponents();
        this.setTitle("Dodaj mecz");
        lblGospodarze.setText(gospodarze);
        lblGoscie.setText(goscie);
        this.idMeczu = idMeczu;
    }

    public boolean idAdded() {
        return added;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldGosc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldGosp = new javax.swing.JTextField();
        lblGoscie = new javax.swing.JLabel();
        lblGospodarze = new javax.swing.JLabel();
        lblKurs = new javax.swing.JLabel();
        lblKursZak = new javax.swing.JLabel();
        btnPrzelicz = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Wprowadź wynik:");

        jLabel2.setText(":");

        lblGoscie.setText("jLabel3");

        lblGospodarze.setText("jLabel3");

        lblKurs.setText("Kurs:");

        lblKursZak.setText("Kurs zakładu:");

        btnPrzelicz.setText("Przelicz kurs");
        btnPrzelicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrzeliczActionPerformed(evt);
            }
        });

        jButton1.setText("Anuluj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dodaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldGosc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(lblGoscie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGospodarze)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldGosp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrzelicz))))
                    .addComponent(lblKurs)
                    .addComponent(lblKursZak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGoscie)
                    .addComponent(lblGospodarze))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldGosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fieldGosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrzelicz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKursZak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrzeliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrzeliczActionPerformed
        lblKurs.setText("Kurs: 1");
        lblKursZak.setText("Kurs zakładu: 1");
    }//GEN-LAST:event_btnPrzeliczActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        short wynikGosc;
        short wynikGosp;
        try {
            wynikGosc = Short.parseShort(fieldGosc.getText());
            wynikGosp = Short.parseShort(fieldGosp.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Wyniki powinny byc libczami",
                    "Błąd formoatu danych",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        Zaklad.getInstance().addZakladSkladowy(new ZakladSkladowy(this.idMeczu, this.kurs, wynikGosc, wynikGosp));
        added = true;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrzelicz;
    private javax.swing.JTextField fieldGosc;
    private javax.swing.JTextField fieldGosp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGoscie;
    private javax.swing.JLabel lblGospodarze;
    private javax.swing.JLabel lblKurs;
    private javax.swing.JLabel lblKursZak;
    // End of variables declaration//GEN-END:variables
}
